### ISSUE TITLE
Problems flashing

### ISSUE THREAD

**Issue by humpejunior** [BernhardSchlegel/Brick-32#7]
Neither with Mac or PC a flash is successful. How do I check whether the TR320 is in flash mode? There is no change with any of the LEDs.
How do I check if 3.3V Power is delivered?
And do I need to connect 220V while trying to flash?

I wasn't finding answers for these questions here on git or your blog...

Flash download tool on PC is just idling and no log file...

Thanks for helping :)

**Comment by BernhardSchlegel** [comment]
Hey hey,

thanks for reaching out, it's not you ;) 

- There is no easy way to check whether it's in flash mode. Only way to tell if flashing starts successfully.
- With a multimeter set to voltage. If you don't have one at your disposal you could setup a voltage divider with a LED, but that cumbersome. Trust the jumper ;) 
- Sometimes, when the relay wants to turn "ON" this consumes too much power. In this case AC or a stronger 3V3 power (other than the COM converter) need to be connected. Carefull with AC, consult an expert if you yourself aren't one.

Maybe also reach out in the forum: There is a topic on this (on german but machine translation works nice these days): https://forum.bierbot.com/viewtopic.php?t=78

Most importantly: Please share with us when you figure it out!

Thanks for trying!

Cheers,
Bernhard.

**Comment by humpejunior** [comment]
Well,

I now connected the Brick with a sufficient 12V/3A DC power supply and a regulator for 3.3V.

Still no connection... 🙃

Any suggestions?
Resolder the connections? Change the rainbow cables? I'll try on windows on Monday. I just now tried with esptool.py in Mac terminal.

The usb-serial gets recognized and the FTDI serial converter is blinking but no connection.![image](https://github.com/BernhardSchlegel/Brick-32/assets/149880761/cacb28ca-f0c7-4c44-a268-360832d38343)

**Comment by BernhardSchlegel** [comment]
Do you have an image of the rainbow cable how it's connected to the pinheader?

**Comment by humpejunior** [comment]
![image](https://github.com/BernhardSchlegel/Brick-32/assets/149880761/e50f90bb-4206-4069-96e2-967e1d6b82f1)

**Comment by BernhardSchlegel** [comment]
I think you connected RX to RX and TX to TX?

**Comment by humpejunior** [comment]
![image](https://github.com/BernhardSchlegel/Brick-32/assets/149880761/d66c6366-b4f8-4083-8cf5-8b1f2c5a12c7)
![image](https://github.com/BernhardSchlegel/Brick-32/assets/149880761/7decb41d-455a-44f1-9a2f-03e400a53478)

Nope...🙂 orange is at RX at the ESP and on TX at the usb serial
And vice versa for the yellow cable.

**Comment by BernhardSchlegel** [comment]
Touché...

Any signs of life from your board when you supply power? Any chance you can do a simple video of your procedure, upload it to YouTube and share it here?

**Comment by humpejunior** [comment]
Yeah... when I supply AC, it turns on an even the default WiFi is visible.

But no signs via DC power.

**Comment by humpejunior** [comment]
Sorry for not uploading the vid!
I wanted to try out some possible sources of erro.

I resoldered everything, tried it with external 3V3 power and no connection.
Then went back to the USB 3V3 Power and voila...
Suddenly connection!

I no finally flashed the esp via the esptool.py and python on a Mac.

If you'd like to, I'll post in detail how I did it on a Mac.

I just switched it on and connected it! It works...

**Comment by humpejunior** [comment]
P.S.:
I just flashed a second brick...

No problems at all! Must've been bad luck with one of the soldering points!

**Comment by BernhardSchlegel** [comment]
Glad to hear it worked! If you could contribute a Mac tutorial that would be awesome as I don't have a Mac. If you write it in Markdown, I can add it to docs.bierbot.com?

**Comment by humpejunior** [comment]
I'd love to! 

As I wanted to erase all error sources, I also ordered a third esp. Well, now I have three bricks and a Hydrometer laying around. I think I need to subscribe to one of your pay plans now🤗👍🏼

**Comment by BernhardSchlegel** [comment]
I've compiled a list of typical causes for flashing problems in the FAQ: https://docs.bierbot.com/getting-started/faq#i-have-problems-flashing-the-esp32 

closing
